// Feature lists mirror app SSOT features/billing/domain/plan-feature-matrix.ts — keep in sync.
// `name` = internal enum key (find/filter). `displayName` = customer-facing label.
// Reposicionamiento "Potencia de LIMS" (2026-06-06): BASIC→Esencial, PREMIUM→Pro;
// Premium/Élite = teasers (soon). Sin web/hosting/white-label. Ver brain/Plan-Tiers.md.
import type { PricingPlan } from "./types";
import { APP_URL } from "./config";

const WA_DEMO = "https://wa.me/529904147791?text=Hola,%20me%20gustar%C3%ADa%20solicitar%20una%20demo%20de%20Lab2Next";

export const PRICING_PLANS: PricingPlan[] = [
  {
    name: "FREE",
    displayName: "Free",
    tagline: "Prueba Lab2Next sin costo. Digitaliza tu operación desde el primer día.",
    prices: {
      MXN: { monthly: 0, yearly: 0 },
      USD: { monthly: 0, yearly: 0 },
      COP: { monthly: 0, yearly: 0 },
    },
    note: "1 sucursal · 1 usuario · 25 exámenes/mes",
    cta: "Crear cuenta gratis",
    ctaHref: `${APP_URL}/register`,
    ctaIntent: "primary",
    external: false,
    features: [
      { text: "Gestión de órdenes y pacientes", included: true },
      { text: "Catálogo editable con tus precios", included: true },
      { text: "Paquetes de exámenes", included: true },
      { text: "Médicos referidores", included: true },
      { text: "Portal de resultados con QR", included: false },
      { text: "WhatsApp y correo", included: false },
      { text: "Caja, cobros e inventario", included: false },
      { text: "PDF de resultados avanzado", included: false },
    ],
  },
  {
    name: "BASIC",
    displayName: "Esencial",
    tagline: "Para entregar resultados como un laboratorio moderno.",
    prices: {
      MXN: { monthly: 749, yearly: 624 },
      USD: { monthly: 44, yearly: 37 },
      COP: { monthly: 170000, yearly: 142000 },
    },
    note: "1 sucursal · hasta 5 usuarios",
    cta: "Crear cuenta gratis",
    ctaHref: `${APP_URL}/register`,
    ctaIntent: "primary",
    external: false,
    features: [
      { text: "Todo lo del plan Free, más:", included: true },
      { text: "Portal de resultados con QR", included: true },
      { text: "WhatsApp y correo", included: true },
      { text: "Agenda de citas", included: true },
      { text: "Captura con fórmulas inteligentes", included: true },
      { text: "Caja, cobros e inventario de insumos", included: true },
      { text: "Sucursales e interfaces extra con costo adicional", included: true },
      { text: "Chat de soporte en la plataforma", included: true },
      { text: "PDF de resultados avanzado", included: false },
    ],
  },
  {
    name: "FOUNDER",
    displayName: "Founder",
    tagline: "Acceso completo de por vida. Solo para los primeros 20 laboratorios.",
    prices: {
      MXN: { monthly: 549, yearly: 549 },
      USD: { monthly: 32, yearly: 32 },
      COP: { monthly: 125000, yearly: 125000 },
    },
    note: "2 sucursales · hasta 15 usuarios · precio congelado de por vida",
    cta: "Asegurar mi cupo",
    ctaHref: `${APP_URL}/register`,
    ctaIntent: "teal",
    external: false,
    featured: true,
    badge: "Tiempo limitado · 20 cupos",
    spotsLeft: 15,
    features: [
      { text: "Todo lo del plan Esencial, más:", included: true },
      { text: "Diseñador de PDF avanzado", included: true },
      { text: "Finanzas: honorarios médicos y reportes", included: true },
      { text: "Inventario con lotes, caducidades y alertas", included: true },
      { text: "Impresión de etiquetas", included: true },
      { text: "Hasta 3 interfaces con tus equipos", included: true },
      { text: "Sucursales e interfaces extra a precio preferencial de por vida", included: true },
      { text: "Chat de soporte prioritario", included: true },
      { text: "Precio fundador congelado para siempre", included: true },
    ],
  },
  {
    name: "PREMIUM",
    displayName: "Pro",
    tagline: "Administra tu laboratorio de punta a punta.",
    prices: {
      MXN: { monthly: 1249, yearly: 1041 },
      USD: { monthly: 73, yearly: 61 },
      COP: { monthly: 285000, yearly: 237000 },
    },
    note: "2 sucursales · hasta 15 usuarios",
    cta: "Crear cuenta gratis",
    ctaHref: `${APP_URL}/register`,
    ctaIntent: "primary",
    external: false,
    features: [
      { text: "Todo lo del plan Esencial, más:", included: true },
      { text: "Diseñador de PDF avanzado", included: true },
      { text: "Finanzas: honorarios médicos y reportes", included: true },
      { text: "Inventario con lotes, caducidades y alertas", included: true },
      { text: "Impresión de etiquetas", included: true },
      { text: "Interfaces con tus equipos de análisis", included: true },
      { text: "Sucursales e interfaces extra con costo adicional", included: true },
      { text: "Chat de soporte prioritario", included: true },
    ],
  },
  {
    name: "PREMIUM_TIER",
    displayName: "Premium",
    soon: true,
    badge: "Próximamente",
    tagline: "Para laboratorios en crecimiento con más sucursales.",
    prices: {
      MXN: { monthly: 1649, yearly: 1374 },
      USD: { monthly: 97, yearly: 81 },
      COP: { monthly: 376000, yearly: 313000 },
    },
    note: "3 sucursales · soporte prioritario",
    cta: "Próximamente",
    ctaHref: WA_DEMO,
    ctaIntent: "primary",
    external: true,
    features: [
      { text: "Todo lo del plan Pro, más:", included: true },
      { text: "3 sucursales", included: true },
      { text: "Más interfaces con tus equipos", included: true },
      { text: "Chat de soporte prioritario", included: true },
      { text: "Sucursales e interfaces extra con costo adicional", included: true },
    ],
  },
  {
    name: "ELITE",
    displayName: "Élite",
    soon: true,
    badge: "Próximamente",
    tagline: "Escala para cadenas y operaciones de alto volumen.",
    prices: {
      MXN: { monthly: 2499, yearly: 2083 },
      USD: { monthly: 147, yearly: 122 },
      COP: { monthly: 570000, yearly: 475000 },
    },
    note: "4 sucursales · soporte de alta prioridad",
    cta: "Próximamente",
    ctaHref: WA_DEMO,
    ctaIntent: "primary",
    external: true,
    features: [
      { text: "Todo lo del plan Premium, más:", included: true },
      { text: "4 sucursales", included: true },
      { text: "Chat de soporte de alta prioridad", included: true },
      { text: "Escala para cadenas", included: true },
      { text: "Sucursales e interfaces extra con costo adicional", included: true },
    ],
  },
  {
    name: "ENTERPRISE",
    displayName: "Enterprise",
    tagline: "No un paquete cerrado. Nos sentamos contigo y diseñamos lo que tu cadena necesita.",
    priceCustom: true,
    note: "Precio a la medida · diseñado según tu operación",
    cta: "Hablar con ventas",
    ctaHref: WA_DEMO,
    ctaIntent: "primary",
    external: true,
    features: [
      { text: "Todo lo del plan Élite, más:", included: true },
      { text: "Escala y módulos según tu operación", included: true },
      { text: "SLA personalizado", included: true },
      { text: "Gestor de cuenta dedicado", included: true },
      { text: "Interfaces a la medida", included: true },
      { text: "Desarrollos a tu operación", included: true },
    ],
  },
];
